version: "3.8"
services:
  web:
    build:
      context: ./conf/nginx
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./src
        target: /var/www/laravel-angya
      - type: bind
        source: ./conf/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./conf/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf

  app:
    build:
      context: ./conf/php
    working_dir: /var/www/laravel-angya
    volumes:
      - type: bind
        source: ./src
        target: /var/www/laravel-angya

  db:
    image: mysql:5.7
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel-angya
      MYSQL_ROOT_PASSWORD: password

volumes:
  db_data: {}
