version: "3.8"
services:
  web:
    image: nginx:1.20
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./src
        target: /var/www/tanavel-angya
      - type: bind
        source: ./conf/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./conf/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf

  app:
    image: php:7.4-fpm
    volumes:
      - type: bind
        source: ./src
        target: /var/www/tanavel-angya

  db:
    image: mysql:5.7
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  db_data: {}
